### ISSUE TITLE
Evento de novembro

### ISSUE THREAD

**Issue by Mazuh** [NatalJS/community#5]
É just até dia 9 já termos uma programação, pra que eu possa desenrolar o local e tal.

@StefanYohansson proativamente já se predispôs a dar uma palestra excelente ("sobre o devtools do firefox e como o react ajudou a reescreve-lo").

E acho que seria bacana alguma outra palestra* e focar o resto do dia em um minicurso mais voltado pro lado produtivo do JS, criando algum projeto talvez até com Firebase.

*voluntários?

**Comment by Mazuh** [comment]
achado o voluntário pra palestra, grande Neto Guimarães.

**Comment by Mazuh** [comment]
só falta pensarmos num cronograma e timings agora.

**Comment by danielorkae** [comment]
@Mazuh o evento já tem data? como entro no grupo do telegram? ele é público ou só da organização?

**Comment by Mazuh** [comment]
Fala, @danielorkae  :D Ainda não tem data definida, mas será no IMD, então eu só posso confirmar a data 15 dias antes! O link do Telegram geral é https://t.me/natal_js

**Comment by Mazuh** [comment]
Infelizmente não vai rolar o evento de novembro, por motivos de força maior por parte da org. Provavelmente só teremos agora no início das aulas do ano que vem (e espero que os temas possam ser reaproveitados), porém vou focar em outras atividades "natalinas".
